
import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertTriangle } from "lucide-react";

export default function Disclaimer() {
  return (
    <div className="bg-white py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <AlertTriangle className="w-12 h-12 mx-auto text-amber-500" />
          <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mt-4">
            Disclaimer
          </h1>
          <p className="text-lg text-gray-600 mt-2">Last updated: 27/08/2025</p>
        </div>

        <Card className="bg-amber-50 border-amber-200">
          <CardContent className="p-8 space-y-6 text-gray-700 dark:text-gray-300 leading-relaxed">
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-gray-100">For Informational Purposes Only</h2>
            <p>
              The information and calculations provided by CalcMyMoney.co.uk are for general informational and educational purposes only. All information on the site is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or calculation on the site.
            </p>
            
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-gray-100 pt-4">Not Professional Advice</h2>
            <p>
              The use of our calculators does not create a professional-client relationship. The website cannot and does not contain financial advice. The financial information is provided for general informational purposes only and is not a substitute for professional advice. Accordingly, before taking any actions based upon such information, we encourage you to consult with the appropriate professionals.
            </p>

            <h2 className="text-2xl font-semibold text-gray-800 dark:text-gray-100 pt-4">Calculations are Estimates</h2>
            <p>
              The results generated by our calculators are estimates based on the data you provide and current (as of the date of the last update) tax laws and financial formulas. These figures may not reflect your actual financial situation and should be used as a guide only. We do not guarantee the accuracy of any calculation.
            </p>
            
            <h2 className="text-2xl font-semibold text-gray-800 dark:text-gray-100 pt-4">No Guarantees</h2>
            <p>
              Your reliance on any information on the site is solely at your own risk. We do not warrant that the site will be available, uninterrupted, or error-free. Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the site or reliance on any information provided on the site.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
